# Generated by Django 5.0.2 on 2024-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_work',
            field=models.BooleanField(default=False),
        ),
    ]
